# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CBE 41622/61622 Laboratory Instrumentation and Measurement
author: Jeffrey C. Kantor
logo: media/logo-02.png
exclude_patterns: [.DS_Store, "**.ipynb_checkpoints", "**.pytest_cache", "tools"]

# Launch on Google Colab button
launch_buttons:
  notebook_interface: "classic"
  colab_url: "https://colab.research.google.com"

# only build files that appear in toc
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off
    
sphinx:
  extra_extensions:
    - sphinxcontrib.mermaid

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jckantor/cbe61622  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: true
  

  
