
[//]: # (DO NOT EDIT. index.md is generated by nbpages. Make changes to templates/index.md.tpl.)
# CBE 61622  Laboratory Instrumentation and Control

This is a start on a collection of notebooks being developed in support of hands-on instruction in the art of laboratory measurements and instrumentation.

[Tentative syllabus](https://docs.google.com/document/d/1AJdhi-GMqnxdtvPga-AJwrmEDYIetyOMTaHNoAA5tPY/edit?usp=sharing)

{% for line in readme_toc -%}
{{ line }}
{% endfor %}
