
[//]: # (DO NOT EDIT. index.md is generated by nbpages. Make changes to templates/index.md.tpl.)
# CBE Virtual Laboratory

[Tentative syllabus](https://docs.google.com/document/d/1AJdhi-GMqnxdtvPga-AJwrmEDYIetyOMTaHNoAA5tPY/edit?usp=sharing)

{% for line in readme_toc -%}
{{ line }}
{% endfor %}
